### ISSUE TITLE
SSH User ec2-user?

### ISSUE THREAD

**Issue by DanHoerst** [awslabs/aws-transit-vpc#10]
Did the SSH user change for the CSR AMI currently provided in the Cloudformation template? All documentation I can find leads me to `ec2-user` as the user, but logging in as that user asks for a password (when providing the keypair used for the instance).

I've also tried spinning up the AMI by itself without any of the UserData from the Cloudformation script and have the same problem.

**Comment by stevemorad** [comment]
I recently launched the latest Cisco AMI - (16.05.01b) and have no problem logging in with ec2-user with both the template and a stand-alone version as you did.  What AWS marketplace listing for the CSR and version are you using?

**Comment by bobrich** [comment]
If anyone bumps into this in the future, the CloudFormation template initializes the CSR with a configuration different than the one that is created if you just launch the router from the marketplace, which does use the 'ec2-user' account.  The username created by the CloudFormation template is 'automate'.

**Comment by groverlalit** [comment]
@DanHoerst : Can you please confirm if you are able to use "ec2-user" or "automate" to log in to the host?

Pending response from Dan in order to resolve this issue.

**Comment by DanHoerst** [comment]
Yes. In my case, it was an issue with the Userdata run on the instance and had nothing to do with the login user, despite presenting itself in that way. Once the Userdata was fixed I was able to login as `ec2-user`
