### ISSUE TITLE
zip not installed by default in some linux distributions

### ISSUE THREAD

**Issue by jeffbrl** [awslabs/aws-transit-vpc#20]
I noticed the following output after executing ` ./build-s3-dist.sh jbl-bucket-east`.

```
[snip]
./build-s3-dist.sh: line 56: zip: command not found
./build-s3-dist.sh: line 58: zip: command not found
./build-s3-dist.sh: line 59: zip: command not found
Clean up build material in /home/jeffl/aws-transit-vpc/deployment/dist/env
Completed building distribution
jeffl@aws-tools:~/aws-transit-vpc/deployment$ 
```

If desired, I can submit a PR to add error checking to the shell script so that it gracefully bails out.

**Comment by jeffbrl** [comment]
I see that zip installation is listed as an assumption in the comments of build-s3-dist.sh. Perhaps an addition to README.md is needed rather than a check for zip within the script.

**Comment by shsenior** [comment]
Thanks for the feedback. Dependency on ZIP utility is documented as comments inside the build script build-s3-dist.sh. We will look to update the README with an upcoming update.
