### ISSUE TITLE
Member must satisfy regular expression pattern: ^[0-9A-Za-z\.\-_]*(?<!\.)

### ISSUE THREAD

**Issue by cloudoutloud** [awslabs/aws-transit-vpc#32]
Not sure why I getting this error below when running primary account template
--
1 validation error detected: Value '%%BUCKET_NAME%%-eu-west-2' at 'code.s3Bucket' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[0-9A-Za-z\.\-_]*(?<!\.)$ (Service: AWSLambda; Status Code: 400; Error Code: ValidationException; Request ID: ec97d612-b5e2-11e8-b4a9-d703702ca31d)
--

**Comment by hnishar** [comment]
Are you passing the bucket-name when running build-s3-dist.sh? The script will replace %%BUCKET_NAME%% with the user provided bucket name.

./build-s3-dist.sh source-bucket-base-name

Alternatively, the solution can be deployed from https://docs.aws.amazon.com/solutions/latest/cisco-based-transit-vpc/step2.html

**Comment by cloudoutloud** [comment]
Thanks, hnishar 
By understanding was the template create a bucket with random name.
Why do we have to define a source bucket base name?
