### ISSUE TITLE
nat-transparency

### ISSUE THREAD

**Issue by tmarsh** [awslabs/aws-transit-vpc#34]
More of a question than an issue. 
Why was this added to the cloudformation?
+    "ios-config-15=\"no crypto ipsec nat-transparency udp-encapsulation\"\n",

**Comment by stevemorad** [comment]
This command turns off NAT-T, which is not needed for connecting CSRs to VGWs. It makes it easier to troubleshoot without having to worry about whether the IPSEC connection is configured to use NAT-T or not.
