### ISSUE TITLE
Point to updated templates

### ISSUE THREAD

**Issue by wolruf** [awslabs/aws-transit-vpc#36]
The CloudFormation templates are out dated, don't feature eu-west-3 region nor the correct AMIs anymore.
The updated template seems to be this one: https://s3.amazonaws.com/awsmp-fulfillment-cf-templates-prod/9f5a4516-a4c3-4cf1-89d4-105d2200230e.c3bb3cc5-974b-480c-53aa-f671857c1c89.template (found on marketplace)

Should we deprecate the templates in github or update them to warn not to use anymore ?

**Comment by hnishar** [comment]
wolruf@, We are actively working on to publish the updated Cloudformation templates with the correct AMIs.

**Comment by groverlalit** [comment]
The AMI IDs have been updated. Details can be found here:
https://github.com/awslabs/aws-transit-vpc/commit/6d2b160096f1bb1738efb491e8a2b21c94345bfc
