### ISSUE TITLE
template file transit-vpc-primary-account-marketplace.template doesn't exist

### ISSUE THREAD

**Issue by tbugfinder** [awslabs/aws-transit-vpc#39]
This file actually does not exist.

https://github.com/awslabs/aws-transit-vpc/blob/9b47514c993921f5e17c8040f0bea54bcf899bb2/deployment/build-s3-dist.sh#L38

**Comment by mohsenari** [comment]
Hi @tbugfinder thanks for finding this. We omit that file before deploying the source code to Github. That file is only provided to Cisco to update their Marketplace CAR listing. I will add a ticket to remove this line from the shell script to prevent further confusions.
