### ISSUE TITLE
ami-id is not valid for Seoul Region

### ISSUE THREAD

**Issue by ego80v** [awslabs/aws-transit-vpc#4]
I can't deploy TransitVPC for Seoul by latest transit-vpc-primary-account.template file using CloudFormation.
I guess, License Included ami-id "ami-29b26647" for Seoul region, is not valid or deployed.
Please Check ami-id and update.
Thanks.

**Comment by stevemorad** [comment]
The templates have been updated to support Seoul and Ohio regions.
