### ISSUE TITLE
KMS key rotation

### ISSUE THREAD

**Issue by sherryxcheng** [awslabs/aws-transit-vpc#42]
Would it work to make the KMS key auto rotate?

**Comment by groverlalit** [comment]
@sherryxcheng Thanks for reaching out to us. 

Key rotation changes only the CMK's backing key. The CMK is the same logical resource, regardless of whether or how many times its backing key changes. The properties of the CMK do not change. So enabling auto-rotation should work.

For more details please refer this document: https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html

**Comment by sherryxcheng** [comment]
@groverlalit Thanks!
