### ISSUE TITLE
deployment fails - module import error

### ISSUE THREAD

**Issue by kolbashj** [awslabs/aws-transit-vpc#45]
Trying to update our AWS runtime to Python3.7 but the 'push-cisco-config' lambda fails on import.

[ERROR] Runtime.ImportModuleError: Unable to import module 'transit_vpc_push_cisco_config/lambda_function': No module named '_cffi_backend'

**Comment by rakshb** [comment]
@kolbashj Hello, the solution is already using Python3.7. Were to trying to update the runtime in your customized version? Can you detail how we can reproduce the issue?

**Comment by rakshb** [comment]
@kolbashj Hello, we fixed this issue in V5.3.2 released today.

**Comment by kolbashj** [comment]
thank you!
