### ISSUE TITLE
Unable to connect to CSRs via SSH

### ISSUE THREAD

**Issue by bwhaley** [awslabs/aws-transit-vpc#5]
I had the following error in the CSR system log after initial boot:

```
Oct 26 00:04:12.580: %CVAC-3-XML_ERROR: Error while parsing XML from file varied:/ovf-env.xml: error 'XML_ERROR_FRAMING', element '', attribute '', explanation 'Invalid Escape Sequence '5 pass AHk%xp&E**rH''
```

It appears to be unhappy with the special characters in the randomly generated password. I've worked around this by hard coding a password in the template, but you might consider eliminating some special characters from the password generation script.

**Comment by stevemorad** [comment]
Thanks for the feedback. We updated the solution to only generate a password with letters and numbers to avoid this happening in the future.
