### ISSUE TITLE
Why default VPC does not require Elastic IP to connect in internet

### ISSUE THREAD

**Issue by rajasekaran07** [awslabs/aws-transit-vpc#6]
Hello,

I have one small query in default VPC. Why default VPC does not require Elastic IP to connect in internet. As per VPC concept even through we are running our instance in VPC public subnet without attaching elaticIP or ELB we can't connect that instance in internet then how it is working in default VPC without Elastic IP.

Regards,
Raja

**Comment by stevemorad** [comment]
This really isn't an issue with this project.  A default VPC assigns a dynamic public IP address to an instance, much like EC2 Classic, when an instance is launched into a default subnet.  More information about VPC public IP addressing is available here:
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-ip-addressing.html#vpc-public-ipv4-addresses
